algoritmo "semnome"
// Função :
// Autor :
// Data : 21/06/2022
// Seção de Declarações 
var
idade:inteiro
habilitada: logico
dirigir: logico
inicio
escreval("Digite a sua idade: ")
leia(idade)
escreval("Você é habilitada para dirigir?(Apenas Verdadeiro ou Falso) ")
leia(habilitada)

dirigir<- ((idade >= 18) e (habilitada = verdadeiro))

escreval("Possui permissão para dirigir: ",dirigir)


fimalgoritmo
